# Environment Settings
gpu_id: 3

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
mask_ratio: 0.2
loss_type: 'CE'

# Data settings
MAX_ITEM_LIST_LENGTH: 10

# Training Settings
train_batch_size: 256
neg_sampling: null
