# Environment Settings
gpu_id: 0

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.02
loss_type: CE  # ['CE', 'BPR']

similarity_type: dot  # ['dot', 'cos']
tau: 1
cl_loss_type: infonce  # ['dcl', 'infonce']
cl_loss_debiased_type: norm  # ['mean', 'norm']
cl_lambda: 0.1
cl_type: all  # [rs, su, rs_su_x, all]
perturbation: None
noise_eps: 0. # only work if perturbation == True
# rs = reverse supervised aug only
# su = supervised aug only
# rs_su_x = agree supervised aug with reverse supervised aug
# all = rs + su + rs_su_x

# Data settings
MAX_ITEM_LIST_LENGTH: 10
drop_inter_ratio: 0.
drop_user_ratio: 0.

# Training Settings
train_batch_size: 512
neg_sampling: null