wandb_project: bicl4rec

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.02
loss_type: CE  # ['CE', 'BPR']

similarity_type: dot  # ['dot', 'cos']
tau: 1
cl_lambda: 0.1
cl_type: rs+fs
# rs = reverse supervised aug x original seq
# fs = forward supervised aug x original seq
# rs+fs
# fs_drop_x = duorec = forward supervised aug x encode original seq again

# Data settings
MAX_ITEM_LIST_LENGTH: 10

# Training Settings
train_batch_size: 512
train_neg_sample_args: null