gpu_id: 0

embedding_size: 64
hidden_size: 128
num_layers: 1
dropout_prob: 0.3
loss_type: CE


# CL Settings
similarity_type: dot  # ['dot', 'cos']
tau: 1
cl_loss_type: infonce  # ['dcl', 'infonce']
cl_loss_debiased_type: null  # ['mean', 'norm']
cl_lambda: 0.1
cl_type: rs_su  # [rs, su, rs_su_x, all]
perturbation: True
noise_eps: 0.1 # only work if perturbation == True

train_batch_size: 512
neg_sampling: null
