# Environment Settings
gpu_id: 1

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.02
loss_type: CE  # ['CE', 'BPR']

similarity_type: dot  # ['dot', 'cos']
tau: 1
cl_loss_type: infonce  # ['dcl', 'infonce']
# cl_aug_offline_similarity_type: itemcf_iuf
# cl_aug_similarity_topk: 5
cl_lambda: 0.3
cl_type: us_x  # ['us_x', 'un', 'su', 'us', null]
# us_x = agree unsupervised aug with supervised aug
# un = unsupervised aug only
# su = supervised aug only
# us = unsupervised aug only + supervised aug only

# Data settings
MAX_ITEM_LIST_LENGTH: 20

# Training Settings
train_batch_size: 256
neg_sampling: null