# Environment Settings
seed: 1234
show_progress: False
log_wandb: True

# Data settings
load_col:
  inter: [user_id, item_id, rating, timestamp]
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'

# Training Settings
epochs: 9999

# Evaluation Settings
eval_args:
  order: TO
  split: 
    RS: [7, 1, 2]
  mode: full
metrics: [Hit, Precision, NDCG, MAP]
topk: [1, 5, 10, 20, 50]
valid_metric: Hit@20
eval_batch_size: 2048